apiVersion: batch/v1
kind: CronJob
metadata:
  name: norganas-helm-oblivion
  labels:     
    team: {{ .Values.team }}

spec:
  timeZone: {{ .Values.cronjob.timeZone }}
  schedule: {{ .Values.cronjob.schedule }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.authorization.serviceAccountName }}
          imagePullSecrets:
            - name: {{ .Values.image.imagePullSecretName }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: config
                  mountPath: {{ .Values.configs.path }}
                  subPath: {{ .Values.configs.subPath }}
              command:
                - "python"
              args:
                - "src/main.py"
          volumes:
            - name: config
              configMap:
                name: {{ .Values.configs.configMap }}
                      
